import fs from 'node:fs';
import path from 'node:path';

const dataPath = path.resolve('client/src/data/brand_spec_comparison.json');
const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));
const notListed = '官方來源未列';

const base = {
  scan_speed_simplex: notListed,
  scan_speed_duplex: notListed,
  adf_spdf: notListed,
  scan_resolution: notListed,
  duplex_print: notListed,
  first_output: notListed,
  paper_input: notListed,
  max_paper_size: notListed,
  monthly_volume: notListed,
  print_language: notListed,
  security_features: notListed,
  cloud_scan_features: notListed,
  extended_source_url: '',
  extended_source_note: '本欄位使用與原有硬規格相同的官方來源；未公開時不以同系列或第三方資料補值。',
};

const specs = {
  'RICOH|IM C2010': {
    scan_speed_simplex: '80 ppm（ARDF，200／300 dpi；官方頁未分黑白／彩色）',
    scan_speed_duplex: 'ARDF 反轉式送稿；官方頁未單列雙面 ipm',
    adf_spdf: 'ARDF 100 張（標準）',
    scan_resolution: '100–1,200 dpi；1,200 dpi 僅 A5 或更小',
    duplex_print: '標準自動雙面列印',
    first_output: '首張列印：黑白 4.5 秒／彩色 7.0 秒',
    paper_input: '標準 1,200／最大 2,300 張',
    max_paper_size: 'SRA3',
    print_language: '標準 PCL 5c、PCL 6、PostScript 3 模擬、PDF Direct 模擬；選配 Adobe PS3',
    security_features: 'SSD／PDF／安全列印加密、802.1X、WPA3、Windows／LDAP 認證、S/MIME',
    cloud_scan_features: '掃描至 USB、Email、資料夾、URL、SMB、FTP、PDF/A、數位簽署 PDF；可搜尋 PDF 需選配 OCR',
  },
  'RICOH|IM C3010': {
    scan_speed_simplex: '150 ppm（200 dpi）／120 ppm（300 dpi；SPDF）',
    scan_speed_duplex: '300 ppm（200 dpi）／220 ppm（300 dpi；SPDF）',
    adf_spdf: 'SPDF 220 張（標準）',
    scan_resolution: '100–1,200 dpi；1,200 dpi 僅 A5 或更小',
    duplex_print: '標準自動雙面列印',
    first_output: '首張列印：黑白 4.0 秒／彩色 6.6 秒',
    paper_input: '標準 1,200／最大 4,850 張',
    max_paper_size: 'SRA3',
    print_language: '標準 PCL 5c、PCL 6、PostScript 3 模擬、PDF Direct 模擬；選配 Adobe PS3',
    security_features: 'SSD／PDF／安全列印加密、802.1X、WPA3、Windows／LDAP 認證、S/MIME',
    cloud_scan_features: '掃描至 USB、Email、資料夾、URL、SMB、FTP、PDF/A、數位簽署 PDF；可搜尋 PDF 需選配 OCR',
  },
  'RICOH|IM C4510': {
    scan_speed_simplex: '150 ppm（200 dpi）／120 ppm（300 dpi；SPDF）',
    scan_speed_duplex: '300 ppm（200 dpi）／220 ppm（300 dpi；SPDF）',
    adf_spdf: 'SPDF 220 張（標準）',
    scan_resolution: '100–1,200 dpi；1,200 dpi 僅 A5 或更小',
    duplex_print: '標準自動雙面列印',
    first_output: '首張列印：黑白 3.2 秒／彩色 5.2 秒',
    paper_input: '標準 1,200／最大 4,850 張',
    max_paper_size: 'SRA3',
    print_language: '標準 PCL 5c、PCL 6、PostScript 3 模擬、PDF Direct 模擬；選配 Adobe PS3',
    security_features: 'SSD／PDF／安全列印加密、802.1X、WPA3、Windows／LDAP 認證、S/MIME',
    cloud_scan_features: '掃描至 USB、Email、資料夾、URL、SMB、FTP、PDF/A、數位簽署 PDF；可搜尋 PDF 需選配 OCR',
  },
  'FUJIFILM Business Innovation|Apeos C2060': {
    scan_speed_simplex: '80 ppm（黑白／彩色；A4 LEF、200 dpi、掃描至資料夾）',
    scan_speed_duplex: '80 ppm（一段式雙面掃描；同一官方測試條件）',
    adf_spdf: '一段式雙面掃描 DADF 130 張',
    scan_resolution: '200／300／400／600 dpi',
    duplex_print: '支援雙面列印；型錄未單列雙面列印速度',
    first_output: '首張影印：黑白 5.9 秒／彩色 8.1 秒',
    paper_input: '標準 620 張；最大 5,190 張（選配串列紙匣與高容量進紙器）',
    max_paper_size: 'A3／11 × 17 吋',
    print_language: '標準 PCL5／PCL6；選配 Adobe PostScript 3',
    security_features: '本機／遠端／IC 卡認證、私密計費列印、軟體簽章、IP 過濾、TPM 2.0、SSL/TLS、IPsec、S/MIME、WPA3',
    cloud_scan_features: '掃描至 Email、URL、SMB／FTP／SFTP、USB；OCR、Wi-Fi、AirPrint、Mopria 為選配或條件式功能',
  },
  'FUJIFILM Business Innovation|Apeos C2560': {
    scan_speed_simplex: '80 ppm（黑白／彩色；A4 LEF、200 dpi、掃描至資料夾）',
    scan_speed_duplex: '80 ppm（一段式雙面掃描；同一官方測試條件）',
    adf_spdf: '一段式雙面掃描 DADF 130 張',
    scan_resolution: '200／300／400／600 dpi',
    duplex_print: '支援雙面列印；型錄未單列雙面列印速度',
    first_output: '首張影印：黑白 5.9 秒／彩色 8.1 秒',
    paper_input: '標準 620 張；最大 5,190 張（選配串列紙匣與高容量進紙器）',
    max_paper_size: 'A3／11 × 17 吋',
    print_language: '標準 PCL5／PCL6；選配 Adobe PostScript 3',
    security_features: '本機／遠端／IC 卡認證、私密計費列印、軟體簽章、IP 過濾、TPM 2.0、SSL/TLS、IPsec、S/MIME、WPA3',
    cloud_scan_features: '掃描至 Email、URL、SMB／FTP／SFTP、USB；OCR、Wi-Fi、AirPrint、Mopria 為選配或條件式功能',
  },
  'FUJIFILM Business Innovation|Apeos C3060': {
    scan_speed_simplex: '80 ppm（黑白／彩色；A4 LEF、200 dpi、掃描至資料夾）',
    scan_speed_duplex: '80 ppm（一段式雙面掃描；同一官方測試條件）',
    adf_spdf: '一段式雙面掃描 DADF 130 張',
    scan_resolution: '200／300／400／600 dpi',
    duplex_print: '支援雙面列印；型錄未單列雙面列印速度',
    first_output: '首張影印：黑白 4.9 秒／彩色 6.7 秒',
    paper_input: '標準 620 張；最大 5,190 張（選配串列紙匣與高容量進紙器）',
    max_paper_size: 'A3／11 × 17 吋',
    print_language: '標準 PCL5／PCL6；選配 Adobe PostScript 3',
    security_features: '本機／遠端／IC 卡認證、私密計費列印、軟體簽章、IP 過濾、TPM 2.0、SSL/TLS、IPsec、S/MIME、WPA3',
    cloud_scan_features: '掃描至 Email、URL、SMB／FTP／SFTP、USB；OCR、Wi-Fi、AirPrint、Mopria 為選配或條件式功能',
  },
  'FUJIFILM Business Innovation|Apeos C4030': {
    scan_speed_simplex: '53 ppm（黑白／彩色；A4、200 dpi、掃描至資料夾）',
    scan_speed_duplex: '105 ppm（一段式雙面掃描；黑白／彩色）',
    adf_spdf: 'DADF 100 張',
    scan_resolution: '200／300／400／600 dpi',
    duplex_print: '支援雙面列印；型錄未單列雙面列印速度',
    first_output: '首張影印：黑白 7.5 秒／彩色 8.0 秒',
    paper_input: '標準 850 張；最大 2,860 張',
    max_paper_size: 'A4／Legal；手送最長 215.9 × 520 mm',
    print_language: '標準 ART EX；選配 Adobe PostScript 3',
    security_features: '本機／遠端／IC 卡認證、私密計費列印、軟體簽章、IP 過濾、TPM 2.0、SSL/TLS、IPsec、S/MIME、WPA3、ISO/IEC 15408',
    cloud_scan_features: 'USB、Email、URL、SMB／FTP／SFTP、Print Utility、AirPrint、Mopria、Working Folder、Cloud Service Hub、Universal Print；部分須另約',
  },
  'SHARP|BP-50C26': {
    scan_speed_simplex: '最多 80 originals/min（黑白／彩色；A4、送稿器、單面、原廠預設）',
    scan_resolution: '推式 100–600 dpi；拉式最高 9,600 dpi（視掃描區域）',
    duplex_print: '自動雙面功能於產品系列配置；官方頁未單列雙面列印速度',
    first_output: '首張影印：黑白 6.5 秒／彩色 7.6 秒',
    paper_input: '標準 650／最大 6,300 張',
    max_paper_size: 'SRA3',
    print_language: '標準 PCL 6 emulation；選配 Adobe PostScript 3',
    cloud_scan_features: '掃描至 Email、desktop、FTP、SMB、USB 與本機儲存',
  },
  'SHARP|BP-50C36': {
    scan_speed_simplex: '最多 80 originals/min（黑白／彩色；A4、送稿器、單面、原廠預設）',
    scan_resolution: '推式 100–600 dpi；拉式最高 9,600 dpi（視掃描區域）',
    duplex_print: '自動雙面功能於產品系列配置；官方頁未單列雙面列印速度',
    first_output: '首張影印：黑白 4.6 秒／彩色 6.5 秒',
    paper_input: '標準 650／最大 6,300 張',
    max_paper_size: 'SRA3',
    print_language: '標準 PCL 6 emulation；選配 Adobe PostScript 3',
    cloud_scan_features: '掃描至 Email、desktop、FTP、SMB、USB 與本機儲存',
  },
  'SHARP|BP-50C45': {
    scan_speed_simplex: '最多 80 originals/min（黑白／彩色；A4、送稿器、單面、原廠預設）',
    scan_resolution: '推式 100–600 dpi；拉式最高 9,600 dpi（視掃描區域）',
    duplex_print: '自動雙面功能於產品系列配置；官方頁未單列雙面列印速度',
    first_output: '首張影印：黑白 4.6 秒／彩色 6.5 秒',
    paper_input: '標準 650／最大 6,300 張',
    max_paper_size: 'SRA3',
    print_language: '標準 PCL 6 emulation；選配 Adobe PostScript 3',
    cloud_scan_features: '掃描至 Email、desktop、FTP、SMB、USB 與本機儲存',
  },
  'Canon|imageRUNNER ADVANCE DX C3926i': {
    scan_speed_simplex: '雙掃描器 C1：135／135 ipm；BA1：70／70 ipm（黑白／彩色；A4、300 dpi、傳送）',
    scan_speed_duplex: '雙掃描器 C1：270／270 ipm；BA1：35／35 ipm（黑白／彩色；A4、300 dpi、傳送）',
    adf_spdf: '選購雙掃描器 C1 200 張／雙面 BA1 100 張',
    scan_resolution: '傳送／影印掃描最高 600 × 600 dpi',
    duplex_print: '自動雙面列印；52–220 gsm',
    first_output: '首張影印完成：8.4 秒以內（A4）',
    paper_input: '標準 1,200／最大 2,300 張',
    max_paper_size: 'SRA3',
    print_language: '標準 UFR II、PCL6；選配 Adobe PostScript 3',
    security_features: '加密 PDF、裝置／使用者簽章、TLS 1.3、IPSec、802.1X、SNMPv3、WPA3、SSD 加密／鎖定、TPM、完整性驗證',
    cloud_scan_features: 'AirPrint、Mopria、Canon PRINT Business、uniFLOW Online、Universal Print；掃描至 Email、SMB、FTP、WebDAV',
  },
  'Canon|imageRUNNER ADVANCE DX C3930i': {
    scan_speed_simplex: '雙掃描器 C1：135／135 ipm；BA1：70／70 ipm（黑白／彩色；A4、300 dpi、傳送）',
    scan_speed_duplex: '雙掃描器 C1：270／270 ipm；BA1：35／35 ipm（黑白／彩色；A4、300 dpi、傳送）',
    adf_spdf: '選購雙掃描器 C1 200 張／雙面 BA1 100 張',
    scan_resolution: '傳送／影印掃描最高 600 × 600 dpi',
    duplex_print: '自動雙面列印；52–220 gsm',
    first_output: '首張影印完成：6.1 秒以內（A4）',
    paper_input: '標準 1,200／最大 2,300 張',
    max_paper_size: 'SRA3',
    print_language: '標準 UFR II、PCL6；選配 Adobe PostScript 3',
    security_features: '加密 PDF、裝置／使用者簽章、TLS 1.3、IPSec、802.1X、SNMPv3、WPA3、SSD 加密／鎖定、TPM、完整性驗證',
    cloud_scan_features: 'AirPrint、Mopria、Canon PRINT Business、uniFLOW Online、Universal Print；掃描至 Email、SMB、FTP、WebDAV',
  },
  'HP|Color LaserJet Enterprise MFP 5800f': {
    scan_speed_simplex: 'A4 單面最高黑白／彩色 47 ppm／94 ipm（官方原表述）',
    scan_speed_duplex: 'A4 雙面最高黑白 47 ipm／彩色 94 ipm（官方原表述）',
    adf_spdf: 'ADF 100 張；支援雙面掃描',
    scan_resolution: '光學最高 600 dpi；硬體最高 600 × 600 dpi',
    duplex_print: '自動雙面列印',
    first_output: '首張列印 A4：黑白 7.2 秒／彩色 7.9 秒',
    paper_input: '標準 650 張；選配最多三個 550 張紙匣',
    max_paper_size: 'Tray 1 最大 216 × 1,200 mm',
    monthly_volume: '建議 2,000–10,000 頁／最高 80,000 頁',
    print_language: 'XPS、HP PCL 6、HP PCL 5c、HP PostScript Level 3 模擬、native PDF 1.7',
    security_features: 'Kerberos／LDAP／PIN、IPsec、防火牆、802.1X、SNMPv3、儲存加密、安全清除、Memory Shield、SureStart Secure Boot、白名單',
    cloud_scan_features: 'AirPrint、Mopria、Microsoft Universal Print、OCR、OneDrive／SharePoint／Email／網路資料夾／USB／FTP／SFTP',
  },
  'Epson|WorkForce Enterprise AM-C4000': {
    adf_spdf: '內建 ADF；台灣公開頁未列容量',
    duplex_print: '自動雙面列印',
    paper_input: '最大 5,850 張；標準容量未列',
    security_features: '讀卡／登入／PIN 驗證列印管理、雙網路插槽；部分功能屬選配升級',
    cloud_scan_features: 'Document Capture Pro、OCR、掃描至資料夾／Email；部分功能屬選配升級',
  },
  'Konica Minolta|bizhub C361i': {
    adf_spdf: '選購 RADF 或 Dualscan ADF，最多 100 張',
    duplex_print: '自動雙面 A6–SRA3，52–256 g/m²',
    first_output: '首張輸出：黑白／彩色 4.6／6.1 秒',
    paper_input: '標準 1,150／最大 6,650 張',
    max_paper_size: 'A6–SRA3；banner 最長 1,200 × 297 mm',
    monthly_volume: '建議 33,000 頁／最高 175,000 頁',
    print_language: '可直接列印 PDF、XPS、DOCX、XLSX、PPTX、JPEG、TIFF、PS、PCL',
    security_features: 'bizhub SECURE、選配 Bitdefender、Authentication Attack Detection',
    cloud_scan_features: 'AirPrint、Mopria、MarketPlace cloud connectors、Microsoft Entra ID／Google Workspace SSO',
  },
  'Konica Minolta|bizhub 451i': {
    adf_spdf: 'Dualscan ADF 300 張（標準）',
    duplex_print: '自動雙面 A6–SRA3，52–256 g/m²',
    first_output: '首張輸出：3.8 秒',
    paper_input: '標準 1,150／最大 6,650 張',
    max_paper_size: 'A6–SRA3；banner 最長 1,200 × 297 mm',
    monthly_volume: '建議 40,000 頁／最高 200,000 頁',
    print_language: '可直接列印 PDF、XPS、DOCX、XLSX、PPTX、JPEG、TIFF、PS、PCL',
    security_features: 'bizhub SECURE、選配 Bitdefender、Authentication Attack Detection',
    cloud_scan_features: 'AirPrint、Mopria、MarketPlace cloud connectors、Microsoft Entra ID／Google Workspace SSO',
  },
};

data.title = '七品牌 20／30／40 張設備比較平台';
data.checked_date = '2026-08-24';
data.extended_fields = [
  'scan_speed_simplex', 'scan_speed_duplex', 'adf_spdf', 'scan_resolution',
  'duplex_print', 'first_output', 'paper_input', 'max_paper_size', 'monthly_volume',
  'print_language', 'security_features', 'cloud_scan_features', 'extended_source_url', 'extended_source_note',
];
data.extended_scope = 'Second-layer values are recorded only from cited official product pages or official brochures. "官方來源未列" denotes that the cited source does not publish the value; it is not a zero or an inferred value.';
data.records = data.records.map((record) => {
  const key = `${record.brand}|${record.model}`;
  const expanded = {
    ...record,
    ...base,
    ...(specs[key] ?? {}),
    extended_source_url: record.source_url,
  };
  const dataFields = data.extended_fields.filter((field) => !['extended_source_url', 'extended_source_note'].includes(field));
  const unpublished = dataFields.filter((field) => expanded[field] === notListed);
  return {
    ...expanded,
    extended_verified_fields: dataFields.length - unpublished.length,
    extended_unpublished_fields: unpublished,
    extended_coverage: unpublished.length === 0 ? '完整核對' : unpublished.length >= 9 ? '官方欄位未公開' : '部分核對',
  };
});

fs.writeFileSync(dataPath, `${JSON.stringify(data, null, 2)}\n`);
console.log(`Extended ${data.records.length} records; confirmed mappings: ${Object.keys(specs).length}.`);
